from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        Node(
            package='stereo_processor',
            executable='gemini',
            name='stereo_processor',
            parameters=[{
                'left_rect_topic': '/stereo/left/image_rect',
                'right_rect_topic': '/stereo/right/image_rect',
                'left_info_topic': '/stereo/left/camera_info',
                'depth_topic': '/stereo/depth/image_rect',
                'disparity_topic': '/stereo/disparity',
                'model_path': '/workspace/ai/crestereo_iter5.onnx',
            }],
            output='screen',
        ),
        Node(
            package='post_util',
            executable='dual',
            name='split_rectifier',
            parameters=[{
                'input_topic': '/camera/dual/image_raw',
                'left_rect_topic': '/stereo/left/image_rect',
                'right_rect_topic': '/stereo/right/image_rect',
                'left_info_topic': '/stereo/left/camera_info',
                'right_info_topic': '/stereo/right/camera_info',
                'calibration_file': '/workspace/SN15095.conf',
                'image_width': 1280,
                'image_height': 720,
                'resolution': 'HD',
            }],
            output='screen',
        ),
        Node(
            package='zed_streamer',
            executable='opencv_streamer',
            name='opencv_streamer',
            parameters=[{
                'output': '/camera/dual/image_raw',
            }],
            output='screen',
        ),
        
        Node(
            package='rtabmap_odom',
            executable='rgbd_odometry',
            namespace='rtabmap',
            name='rgbd_odometry',
            parameters=[{
                'frame_id': 'camera_link',
                'odom_frame_id': 'odom',
                'approx_sync': True,
                'topic_queue_size': 50,
                'sync_queue_size': 25,
                'wait_for_transform': 0.2,
                'qos': 1,
                'qos_image': 1,
                'Odom/Strategy': '0',
                'Vis/MinInliers': '8',
                'Vis/FeatureType': '6',
                'Vis/CorFlowMaxLevel': '3',
                'Reg/Strategy': '0',
                'Icp/VoxelSize': '0.05',
                'Icp/PointToPlane': 'true',
                'Icp/MaxCorrespondenceDistance': '0.2',
                'Icp/CorrespondenceRatio': '0.2',
                'Odom/ResetCountdown': '10',
                'Odom/MaxFeatures': '0',
            }],
            remappings=[
                ('rgb/image', '/stereo/left/image_rect'),
                ('rgb/camera_info', '/stereo/left/camera_info'),
                ('depth/image', '/stereo/depth/image_rect'),
                ('depth/camera_info', '/stereo/left/camera_info'),
                ('odom', 'odom'),
            ],
            output='screen',
        ),
        Node(
            package='rtabmap_slam',
            executable='rtabmap',
            namespace='rtabmap',
            name='rtabmap',
            parameters=[{
                'database_path': '/tmp/rtabmap.db',
                'frame_id': 'camera_link',
                'approx_sync': True,
                'topic_queue_size': 50,
                'sync_queue_size': 25,
                'qos': 1,
                'qos_image': 1,
                'qos_imu': 1,
                'subscribe_depth': True,
                'subscribe_rgb': True,
                'subscribe_odom_info': False,
                'Mem/IncrementalMemory': 'true',
                'Mem/InitWMWithAllNodes': 'false',
                'Mem/STMSize': '30',
                'Rtabmap/DetectionRate': '1',
                'Mem/RehearsalSimilarity': '0.20',
                'Kp/MaxFeatures': '600',
                'Kp/DetectorStrategy': '6',
                'Vis/MinInliers': '8',
                'Vis/InlierDistance': '0.1',
                'RGBD/ProximityBySpace': 'true',
                'RGBD/ProximityMaxGraphDepth': '50',
                'RGBD/ProximityPathMaxNeighbors': '10',
                'RGBD/AngularUpdate': '0.01',
                'RGBD/LinearUpdate': '0.01',
                'RGBD/OptimizeFromGraphEnd': 'false',
                'RGBD/OptimizeMaxError': '5.0',
                'Optimizer/Strategy': '0',
                'Optimizer/Iterations': '100',
                'Reg/Strategy': '1',
                'Reg/Force3DoF': 'false',
                'Icp/VoxelSize': '0.05',
                'Icp/MaxCorrespondenceDistance': '0.3',
                'Icp/CorrespondenceRatio': '0.1',
                'Icp/Iterations': '50',
                'Icp/PointToPlane': 'true',
                'Grid/RangeMax': '5.0',
                'Grid/RangeMin': '0.3',
                'Grid/CellSize': '0.05',
                'Grid/3D': 'true',
                'Grid/FromDepth': 'true',
                'Rtabmap/TimeThr': '0',
                'Rtabmap/MemoryThr': '0',
                'Mem/BadSignaturesIgnored': 'false',
                'Mem/RehearsalIdUpdatedToNewOne': 'true',
                'Odom/GuessMotion': 'true',
                'Odom/FilteringStrategy': '1',
            }],
            remappings=[
                ('rgb/image', '/stereo/left/image_rect'),
                ('rgb/camera_info', '/stereo/left/camera_info'),
                ('depth/image', '/stereo/depth/image_rect'),
                ('depth/camera_info', '/stereo/left/camera_info'),
                ('odom', 'odom'),
            ],
            output='screen',
        ),
        Node(
            package='rviz2',
            executable='rviz2',
            name='rviz2',
            arguments=['-d', '/workspace/launch/zed_stereo_rtabmap.rviz'],
            output='screen',
        ),
    ])
